### ISSUE TITLE
parsing the KSUID issue

### ISSUE THREAD

**Issue by robbiecode** [tuupola/ksuid#7]
It looks like you users are unable to easily parse the timestamp/payload from the generated string.

When I take your string to the NODEJS version I can identify the time/payload buffer.

Are you planning this feature:

var oid="1cLqD50DQUhZyteK3zbqgP5dHU5";//from php
oid = KSUID.parse(oid);
return [oid,oid.string,oid.date,oid.timestamp];

https://www.npmjs.com/package/ksuid

**Comment by robbiecode** [comment]
I've added option to check TIMESTAMP/EPOCH of any given ID:
The function was added to your /src/Ksuid.php on my dev server:

$ksuid = new Ksuid;
echo $ksuid->Parse('1cMEmaJtIKIZxsPALGX6gD4C0r3');
$dec=json_decode($ksuid->Parse('1cMEmaJtIKIZxsPALGX6gD4C0r3'));
echo $dec->timestamp;

public function Parse($dat): string
{
    $encoded = (new Base62)->decode($dat);
    $hex=bin2hex($encoded);
    $hexpl=bin2hex(substr($encoded,5,20));
    $hexts=bin2hex(substr($encoded,0,4));
    $ts=hexdec($hexts);
    $ep=1400000000+$ts;
    return json_encode(['epoch'=>$ep,'timestamp'=>$ts,'hexid'=>$hex,'hexpl'=>$hexpl,'hexts'=>$hexts]);
}

**Comment by tuupola** [comment]
[README](https://github.com/tuupola/ksuid/blob/2.x/README.md) describes how to retrieve timestamp and payload.

```php
$ksuid = Ksuid::fromString("1cMEmaJtIKIZxsPALGX6gD4C0r3");

print $ksuid->timestamp();
print $ksuid->unixtime();
print bin2hex($ksuid->payload());
```
